### ISSUE TITLE
Need some help to figure out how to run this

### ISSUE THREAD

**Issue by oshai** [bgard6977/depends#3]
Saw the readme and I think it will be nice to get some more info on how to run:
`depends.jar` - where can I obtain it? should I build the repo?
`com.mycompany.app:my-app:1.0-SNAPSHOT` - is this my artifact id? should I run in from maven/gradle dir?

**Comment by avantgardnerio** [comment]
> where can I obtain it? should I build the repo?

Yes, thank you. For now you have to build from source. I will look into:

1. deploying this to maven central as an artifact
2. putting it up as a release on github
3. turning it into a maven / gradle plugin

This is honestly pretty early stage. For now, I updated the readme. Please run `./gradlew build` to build.

> how to run: depends.jar

I've updated that as well. After the build, you will have `build/libs/depends-1.0-SNAPSHOT.jar` so run:

`java -jar build/libs/depends-1.0-SNAPSHOT.jar com.mycompany.app:my-app:1.0-SNAPSHOT --filter=JsonParseException`

> com.mycompany.app:my-app:1.0-SNAPSHOT - is this my artifact id?

Exactly. You'll need to run `mvn install` or `gradle install` on your project, to put build your code and put the resulting jar into your maven/gradle local cache. After you've done that, you can run depends on it.

I'm looking for suggestions on how to make this easier. #3 from the above list was suggested on Hacker News, and that sounds like the best user experience, so I will look into that option.

**Comment by oshai** [comment]
Thanks, I updated the readme to reflect how I understand it: https://github.com/bgard6977/depends/pull/4
I will try to work on it a bit then might have more questions or suggestions. build tool plugin sounds like a nice idea indeed.
