### ISSUE TITLE
Can you use this to find non used classes as well?

### ISSUE THREAD

**Issue by Marcelovk** [bgard6977/depends#5]
Currently the generation of fat jars by spring is huge. A very simple hello world gives more than 10MB in classes. If we can use that to reduce the fatjar sizes it would be very useful

**Comment by avantgardnerio** [comment]
If there are no dynamic method invocations (reflection), you would use this for tree-shaking to reduce the size of your fat jars. You'd just have to change the HashSet operations from a union to an intersection or something.

I've heard that GraalVM does the same thing, so you might want to check that out.

Also, you may want to look into using OSGi to deploy a graph of jars by the maven coordinate. It's equivalent to a fat jar but doesn't increase build time. It can be as simple as using:

https://maven.apache.org/plugins/maven-dependency-plugin/resolve-mojo.html

to download all the jars. Then:

https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html

To build up the (very long) classpath string, then finally:

java -cp ${the-generated-classpath}

to run your app.
